apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  PORT: "{{ .Values.service.port }}"
  DISCOVER_SERVICE_LABEL_SELECTOR: "{{ .Values.configmap.discoverServiceLabelSelector }}"
  NAMESPACE: "{{ .Values.namespace }}"
  SERVICE_NAME: "{{ .Values.service.name }}"